<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Modules\Nomina\Models\ConceptoNomina;
use App\Modules\Nomina\Enums\ClasificacionConcepto;
use App\Modules\Nomina\Enums\TipoConcepto;

class ConceptosNominaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $conceptos = [
            // ========== DEVENGADOS ==========
            
            // Salario y básicos
            [
                'codigo' => '001',
                'nombre' => 'Salario Básico',
                'descripcion' => 'Salario básico mensual del empleado',
                'clasificacion' => ClasificacionConcepto::DEVENGADO,
                'tipo' => TipoConcepto::FIJO,
                'base_salarial' => true,
                'afecta_prestaciones' => true,
                'afecta_seguridad_social' => true,
                'afecta_parafiscales' => true,
                'aplica_retencion' => true,
                'visible_colilla' => true,
                'orden_colilla' => 1,
                'agrupador' => 'Salarios',
                'activo' => true,
                'sistema' => true,
            ],
            [
                'codigo' => '002',
                'nombre' => 'Auxilio de Transporte',
                'descripcion' => 'Auxilio de transporte legal',
                'clasificacion' => ClasificacionConcepto::DEVENGADO,
                'tipo' => TipoConcepto::CALCULADO,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => false,
                'visible_colilla' => true,
                'orden_colilla' => 2,
                'agrupador' => 'Auxilios',
                'activo' => true,
                'sistema' => true,
            ],
            
            // Horas extras
            [
                'codigo' => '010',
                'nombre' => 'Horas Extras Diurnas',
                'descripcion' => 'Horas extras trabajadas en horario diurno (25%)',
                'clasificacion' => ClasificacionConcepto::DEVENGADO,
                'tipo' => TipoConcepto::NOVEDAD,
                'base_salarial' => true,
                'afecta_prestaciones' => true,
                'afecta_seguridad_social' => true,
                'afecta_parafiscales' => true,
                'aplica_retencion' => true,
                'porcentaje' => 25.00,
                'visible_colilla' => true,
                'orden_colilla' => 10,
                'agrupador' => 'Horas Extras',
                'activo' => true,
                'sistema' => false,
            ],
            [
                'codigo' => '011',
                'nombre' => 'Horas Extras Nocturnas',
                'descripcion' => 'Horas extras trabajadas en horario nocturno (75%)',
                'clasificacion' => ClasificacionConcepto::DEVENGADO,
                'tipo' => TipoConcepto::NOVEDAD,
                'base_salarial' => true,
                'afecta_prestaciones' => true,
                'afecta_seguridad_social' => true,
                'afecta_parafiscales' => true,
                'aplica_retencion' => true,
                'porcentaje' => 75.00,
                'visible_colilla' => true,
                'orden_colilla' => 11,
                'agrupador' => 'Horas Extras',
                'activo' => true,
                'sistema' => false,
            ],
            [
                'codigo' => '012',
                'nombre' => 'Horas Extras Dominicales y Festivas',
                'descripcion' => 'Horas extras trabajadas en domingos y festivos (100%)',
                'clasificacion' => ClasificacionConcepto::DEVENGADO,
                'tipo' => TipoConcepto::NOVEDAD,
                'base_salarial' => true,
                'afecta_prestaciones' => true,
                'afecta_seguridad_social' => true,
                'afecta_parafiscales' => true,
                'aplica_retencion' => true,
                'porcentaje' => 100.00,
                'visible_colilla' => true,
                'orden_colilla' => 12,
                'agrupador' => 'Horas Extras',
                'activo' => true,
                'sistema' => false,
            ],
            
            // Recargos
            [
                'codigo' => '020',
                'nombre' => 'Recargo Nocturno',
                'descripcion' => 'Recargo por trabajo nocturno (35%)',
                'clasificacion' => ClasificacionConcepto::DEVENGADO,
                'tipo' => TipoConcepto::NOVEDAD,
                'base_salarial' => true,
                'afecta_prestaciones' => true,
                'afecta_seguridad_social' => true,
                'afecta_parafiscales' => true,
                'aplica_retencion' => true,
                'porcentaje' => 35.00,
                'visible_colilla' => true,
                'orden_colilla' => 20,
                'agrupador' => 'Recargos',
                'activo' => true,
                'sistema' => false,
            ],
            [
                'codigo' => '021',
                'nombre' => 'Recargo Dominical y Festivo',
                'descripcion' => 'Recargo por trabajo en domingo o festivo (75%)',
                'clasificacion' => ClasificacionConcepto::DEVENGADO,
                'tipo' => TipoConcepto::NOVEDAD,
                'base_salarial' => true,
                'afecta_prestaciones' => true,
                'afecta_seguridad_social' => true,
                'afecta_parafiscales' => true,
                'aplica_retencion' => true,
                'porcentaje' => 75.00,
                'visible_colilla' => true,
                'orden_colilla' => 21,
                'agrupador' => 'Recargos',
                'activo' => true,
                'sistema' => false,
            ],
            
            // Comisiones y bonificaciones
            [
                'codigo' => '030',
                'nombre' => 'Comisiones',
                'descripcion' => 'Comisiones por ventas o cumplimiento de metas',
                'clasificacion' => ClasificacionConcepto::DEVENGADO,
                'tipo' => TipoConcepto::NOVEDAD,
                'base_salarial' => true,
                'afecta_prestaciones' => true,
                'afecta_seguridad_social' => true,
                'afecta_parafiscales' => true,
                'aplica_retencion' => true,
                'visible_colilla' => true,
                'orden_colilla' => 30,
                'agrupador' => 'Otros Ingresos',
                'activo' => true,
                'sistema' => false,
            ],
            [
                'codigo' => '031',
                'nombre' => 'Bonificación',
                'descripcion' => 'Bonificación especial no constitutiva de salario',
                'clasificacion' => ClasificacionConcepto::DEVENGADO,
                'tipo' => TipoConcepto::NOVEDAD,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => true,
                'visible_colilla' => true,
                'orden_colilla' => 31,
                'agrupador' => 'Otros Ingresos',
                'activo' => true,
                'sistema' => false,
            ],
            
            // Prestaciones sociales
            [
                'codigo' => '040',
                'nombre' => 'Prima de Servicios',
                'descripcion' => 'Prima de servicios semestral',
                'clasificacion' => ClasificacionConcepto::DEVENGADO,
                'tipo' => TipoConcepto::CALCULADO,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => true,
                'visible_colilla' => true,
                'orden_colilla' => 40,
                'agrupador' => 'Prestaciones',
                'activo' => true,
                'sistema' => true,
            ],
            [
                'codigo' => '041',
                'nombre' => 'Cesantías',
                'descripcion' => 'Cesantías consolidadas',
                'clasificacion' => ClasificacionConcepto::DEVENGADO,
                'tipo' => TipoConcepto::CALCULADO,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => false,
                'visible_colilla' => true,
                'orden_colilla' => 41,
                'agrupador' => 'Prestaciones',
                'activo' => true,
                'sistema' => true,
            ],
            [
                'codigo' => '042',
                'nombre' => 'Intereses sobre Cesantías',
                'descripcion' => 'Intereses sobre cesantías (12% anual)',
                'clasificacion' => ClasificacionConcepto::DEVENGADO,
                'tipo' => TipoConcepto::CALCULADO,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => false,
                'visible_colilla' => true,
                'orden_colilla' => 42,
                'agrupador' => 'Prestaciones',
                'activo' => true,
                'sistema' => true,
            ],
            [
                'codigo' => '043',
                'nombre' => 'Vacaciones',
                'descripcion' => 'Vacaciones causadas y pagadas',
                'clasificacion' => ClasificacionConcepto::DEVENGADO,
                'tipo' => TipoConcepto::CALCULADO,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => true,
                'visible_colilla' => true,
                'orden_colilla' => 43,
                'agrupador' => 'Prestaciones',
                'activo' => true,
                'sistema' => true,
            ],
            
            // ========== DEDUCCIONES ==========
            
            // Seguridad Social - Empleado
            [
                'codigo' => '100',
                'nombre' => 'Aporte Salud',
                'descripcion' => 'Aporte a salud del empleado (4%)',
                'clasificacion' => ClasificacionConcepto::DEDUCIDO,
                'tipo' => TipoConcepto::CALCULADO,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => false,
                'porcentaje' => 4.00,
                'visible_colilla' => true,
                'orden_colilla' => 100,
                'agrupador' => 'Seguridad Social',
                'activo' => true,
                'sistema' => true,
            ],
            [
                'codigo' => '101',
                'nombre' => 'Aporte Pensión',
                'descripcion' => 'Aporte a pensión del empleado (4%)',
                'clasificacion' => ClasificacionConcepto::DEDUCIDO,
                'tipo' => TipoConcepto::CALCULADO,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => false,
                'porcentaje' => 4.00,
                'visible_colilla' => true,
                'orden_colilla' => 101,
                'agrupador' => 'Seguridad Social',
                'activo' => true,
                'sistema' => true,
            ],
            [
                'codigo' => '102',
                'nombre' => 'Fondo de Solidaridad Pensional',
                'descripcion' => 'Aporte al fondo de solidaridad pensional (1% o 2%)',
                'clasificacion' => ClasificacionConcepto::DEDUCIDO,
                'tipo' => TipoConcepto::CALCULADO,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => false,
                'porcentaje' => 1.00,
                'visible_colilla' => true,
                'orden_colilla' => 102,
                'agrupador' => 'Seguridad Social',
                'activo' => true,
                'sistema' => true,
            ],
            
            // Retención en la fuente
            [
                'codigo' => '110',
                'nombre' => 'Retención en la Fuente',
                'descripcion' => 'Retención en la fuente sobre salarios',
                'clasificacion' => ClasificacionConcepto::DEDUCIDO,
                'tipo' => TipoConcepto::CALCULADO,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => false,
                'visible_colilla' => true,
                'orden_colilla' => 110,
                'agrupador' => 'Retenciones',
                'activo' => true,
                'sistema' => true,
            ],
            
            // Otras deducciones
            [
                'codigo' => '120',
                'nombre' => 'Préstamo',
                'descripcion' => 'Descuento por préstamo a empleado',
                'clasificacion' => ClasificacionConcepto::DEDUCIDO,
                'tipo' => TipoConcepto::NOVEDAD,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => false,
                'visible_colilla' => true,
                'orden_colilla' => 120,
                'agrupador' => 'Otros Descuentos',
                'activo' => true,
                'sistema' => false,
            ],
            [
                'codigo' => '121',
                'nombre' => 'Embargo Judicial',
                'descripcion' => 'Embargo por orden judicial',
                'clasificacion' => ClasificacionConcepto::DEDUCIDO,
                'tipo' => TipoConcepto::NOVEDAD,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => false,
                'visible_colilla' => true,
                'orden_colilla' => 121,
                'agrupador' => 'Otros Descuentos',
                'activo' => true,
                'sistema' => false,
            ],
            [
                'codigo' => '122',
                'nombre' => 'Cuota Sindical',
                'descripcion' => 'Cuota sindical',
                'clasificacion' => ClasificacionConcepto::DEDUCIDO,
                'tipo' => TipoConcepto::FIJO,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => false,
                'visible_colilla' => true,
                'orden_colilla' => 122,
                'agrupador' => 'Otros Descuentos',
                'activo' => true,
                'sistema' => false,
            ],
            
            // ========== NO IMPUTABLES ==========
            
            [
                'codigo' => '200',
                'nombre' => 'Incapacidad',
                'descripcion' => 'Días de incapacidad',
                'clasificacion' => ClasificacionConcepto::NO_IMPUTABLE,
                'tipo' => TipoConcepto::NOVEDAD,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => false,
                'visible_colilla' => true,
                'orden_colilla' => 200,
                'agrupador' => 'Ausencias',
                'activo' => true,
                'sistema' => false,
            ],
            [
                'codigo' => '201',
                'nombre' => 'Licencia No Remunerada',
                'descripcion' => 'Días de licencia no remunerada',
                'clasificacion' => ClasificacionConcepto::NO_IMPUTABLE,
                'tipo' => TipoConcepto::NOVEDAD,
                'base_salarial' => false,
                'afecta_prestaciones' => false,
                'afecta_seguridad_social' => false,
                'afecta_parafiscales' => false,
                'aplica_retencion' => false,
                'visible_colilla' => true,
                'orden_colilla' => 201,
                'agrupador' => 'Ausencias',
                'activo' => true,
                'sistema' => false,
            ],
        ];

        foreach ($conceptos as $concepto) {
            ConceptoNomina::create($concepto);
        }
    }
}