<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Modules\Nomina\Models\Contrato;
use App\Modules\Nomina\Models\CentroCosto;

class ContratosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('📋 Creando contratos de prestación de servicios...');
        
        $centrosCosto = CentroCosto::all();

        $contratos = [
            // ════ ACTIVOS (8 contratos) ════
            [
                'numero_contrato' => 'CT-2026-001',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->startOfMonth(),
                'fecha_fin' => now()->addMonths(6)->endOfMonth(),
                'plazo_meses' => 6,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '1234567890',
                'nombre_contratista' => 'Juan Carlos Rodríguez Pérez',
                'email_contratista' => 'juan.rodriguez@example.com',
                'telefono_contratista' => '3101234567',
                'direccion_contratista' => 'Calle 123 # 45-67',
                'ciudad_contratista' => 'Bogotá',
                'valor_total' => 18000000,
                'valor_mensual' => 3000000,
                'valor_pagado' => 0,
                'saldo_pendiente' => 18000000,
                'objeto' => 'Desarrollo de software para módulo de nómina',
                'obligaciones' => 'Desarrollar componentes de software, asistir a reuniones de seguimiento, documentar código',
                'supervisor_nombre' => 'María García',
                'centro_costo_id' => $centrosCosto->where('codigo', '004001')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 10.00,
                'aplica_retencion_ica' => false,
                'porcentaje_retencion_ica' => 0,
                'aplica_estampilla' => false,
                'porcentaje_estampilla' => 0,
                'banco' => 'Bancolombia',
                'tipo_cuenta' => 'ahorros',
                'numero_cuenta' => '12345678901',
                'requiere_seguridad_social' => true,
                'adjunta_planilla_pago' => true,
                'requiere_poliza' => false,
                'estado' => 'activo',
            ],
            [
                'numero_contrato' => 'CT-2026-002',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->subMonths(2)->startOfMonth(),
                'fecha_fin' => now()->addMonths(4)->endOfMonth(),
                'plazo_meses' => 6,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '9876543210',
                'nombre_contratista' => 'Ana María López Torres',
                'email_contratista' => 'ana.lopez@example.com',
                'telefono_contratista' => '3209876543',
                'direccion_contratista' => 'Carrera 45 # 67-89',
                'ciudad_contratista' => 'Bogotá',
                'valor_total' => 24000000,
                'valor_mensual' => 4000000,
                'valor_pagado' => 8000000,
                'saldo_pendiente' => 16000000,
                'objeto' => 'Asesoría contable y financiera del módulo contabilidad',
                'obligaciones' => 'Asesoría en parametrización, capacitación al personal, elaboración de manuales',
                'supervisor_nombre' => 'Pedro Martínez',
                'centro_costo_id' => $centrosCosto->where('codigo', '001003')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 11.00,
                'aplica_retencion_ica' => false,
                'porcentaje_retencion_ica' => 0,
                'aplica_estampilla' => false,
                'porcentaje_estampilla' => 0,
                'banco' => 'Banco de Bogotá',
                'tipo_cuenta' => 'corriente',
                'numero_cuenta' => '98765432109',
                'requiere_seguridad_social' => true,
                'adjunta_planilla_pago' => true,
                'requiere_poliza' => true,
                'numero_poliza' => 'POL-2026-001',
                'aseguradora' => 'Seguros Bolívar',
                'fecha_vencimiento_poliza' => now()->addMonths(6),
                'estado' => 'activo',
            ],
            [
                'numero_contrato' => 'CT-2026-003',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->startOfMonth(),
                'fecha_fin' => now()->addMonths(3)->endOfMonth(),
                'plazo_meses' => 3,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '5555666677',
                'nombre_contratista' => 'Carlos Eduardo Ramírez Sánchez',
                'email_contratista' => 'carlos.ramirez@example.com',
                'telefono_contratista' => '3157890123',
                'direccion_contratista' => 'Avenida 68 # 12-34',
                'ciudad_contratista' => 'Bogotá',
                'valor_total' => 9000000,
                'valor_mensual' => 3000000,
                'valor_pagado' => 0,
                'saldo_pendiente' => 9000000,
                'objeto' => 'Diseño gráfico y contenidos para campañas marketing',
                'obligaciones' => 'Diseñar piezas gráficas, crear contenido visual, entregar archivos editables',
                'supervisor_nombre' => 'Laura Fernández',
                'centro_costo_id' => $centrosCosto->where('codigo', '003003')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 10.00,
                'aplica_retencion_ica' => true,
                'porcentaje_retencion_ica' => 0.966,
                'aplica_estampilla' => false,
                'porcentaje_estampilla' => 0,
                'banco' => 'Davivienda',
                'tipo_cuenta' => 'ahorros',
                'numero_cuenta' => '44455566677',
                'requiere_seguridad_social' => false,
                'adjunta_planilla_pago' => false,
                'requiere_poliza' => false,
                'estado' => 'activo',
            ],
            [
                'numero_contrato' => 'CT-2026-004',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->subMonths(1)->startOfMonth(),
                'fecha_fin' => now()->addMonths(5)->endOfMonth(),
                'plazo_meses' => 6,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '1111222233',
                'nombre_contratista' => 'Rodrigo Fernández Gutiérrez',
                'email_contratista' => 'rodrigo.fernandez@example.com',
                'telefono_contratista' => '3161234567',
                'direccion_contratista' => 'Calle 75 # 30-50',
                'ciudad_contratista' => 'Bogotá',
                'valor_total' => 20000000,
                'valor_mensual' => 3333333,
                'valor_pagado' => 3333333,
                'saldo_pendiente' => 16666667,
                'objeto' => 'Consultoría en infraestructura tecnológica',
                'obligaciones' => 'Diagnóstico tecnológico, diseño de arquitectura, implementación',
                'supervisor_nombre' => 'Miguel Torres',
                'centro_costo_id' => $centrosCosto->where('codigo', '004002')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 11.00,
                'aplica_retencion_ica' => false,
                'porcentaje_retencion_ica' => 0,
                'aplica_estampilla' => false,
                'porcentaje_estampilla' => 0,
                'banco' => 'Bancolombia',
                'tipo_cuenta' => 'corriente',
                'numero_cuenta' => '12348765432',
                'requiere_seguridad_social' => true,
                'adjunta_planilla_pago' => true,
                'requiere_poliza' => true,
                'numero_poliza' => 'POL-2026-002',
                'aseguradora' => 'ACE Seguros',
                'fecha_vencimiento_poliza' => now()->addMonths(5),
                'estado' => 'activo',
            ],
            [
                'numero_contrato' => 'CT-2026-005',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->startOfMonth(),
                'fecha_fin' => now()->addMonths(12)->endOfMonth(),
                'plazo_meses' => 12,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '3333444455',
                'nombre_contratista' => 'Sandra López García',
                'email_contratista' => 'sandra.lopez@example.com',
                'telefono_contratista' => '3171111111',
                'direccion_contratista' => 'Carrera 30 # 50-70',
                'ciudad_contratista' => 'Bogotá',
                'valor_total' => 60000000,
                'valor_mensual' => 5000000,
                'valor_pagado' => 0,
                'saldo_pendiente' => 60000000,
                'objeto' => 'Servicios de asesoría legal corporativa',
                'obligaciones' => 'Asesoría legal, revisión de contratos, soporte en litigios',
                'supervisor_nombre' => 'Gerencia General',
                'centro_costo_id' => $centrosCosto->where('codigo', '001001')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 10.00,
                'aplica_retencion_ica' => false,
                'porcentaje_retencion_ica' => 0,
                'aplica_estampilla' => true,
                'porcentaje_estampilla' => 3.0,
                'banco' => 'BBVA',
                'tipo_cuenta' => 'corriente',
                'numero_cuenta' => '55556666777',
                'requiere_seguridad_social' => false,
                'adjunta_planilla_pago' => false,
                'requiere_poliza' => false,
                'estado' => 'activo',
            ],
            [
                'numero_contrato' => 'CT-2026-006',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->subMonths(1)->startOfMonth(),
                'fecha_fin' => now()->addMonths(8)->endOfMonth(),
                'plazo_meses' => 9,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '5555666677',
                'nombre_contratista' => 'Jaime Caldas Montoya',
                'email_contratista' => 'jaime.caldas@example.com',
                'telefono_contratista' => '3182222222',
                'direccion_contratista' => 'Avenida 100 # 30-40',
                'ciudad_contratista' => 'Medellín',
                'valor_total' => 36000000,
                'valor_mensual' => 4000000,
                'valor_pagado' => 4000000,
                'saldo_pendiente' => 32000000,
                'objeto' => 'Auditoría externa y control interno',
                'obligaciones' => 'Auditoría anual, evaluación de riesgos, recomendaciones de mejora',
                'supervisor_nombre' => 'Contador Principal',
                'centro_costo_id' => $centrosCosto->where('codigo', '001003')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 11.00,
                'aplica_retencion_ica' => false,
                'porcentaje_retencion_ica' => 0,
                'aplica_estampilla' => false,
                'porcentaje_estampilla' => 0,
                'banco' => 'Banco de Bogotá',
                'tipo_cuenta' => 'ahorros',
                'numero_cuenta' => '77778888999',
                'requiere_seguridad_social' => false,
                'adjunta_planilla_pago' => false,
                'requiere_poliza' => false,
                'estado' => 'activo',
            ],
            [
                'numero_contrato' => 'CT-2026-007',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->addDays(15),
                'fecha_fin' => now()->addMonths(4)->endOfMonth(),
                'plazo_meses' => 3,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '7777888899',
                'nombre_contratista' => 'Valentina Ruiz Espinosa',
                'email_contratista' => 'valentina.ruiz@example.com',
                'telefono_contratista' => '3193333333',
                'direccion_contratista' => 'Calle 85 # 20-45',
                'ciudad_contratista' => 'Bogotá',
                'valor_total' => 12000000,
                'valor_mensual' => 4000000,
                'valor_pagado' => 0,
                'saldo_pendiente' => 12000000,
                'objeto' => 'Capacitación en sistemas integrados de gestión',
                'obligaciones' => 'Diseñar y dictar capacitación, elaborar material didáctico, evaluar aprendizaje',
                'supervisor_nombre' => 'Jefe de RRHH',
                'centro_costo_id' => $centrosCosto->where('codigo', '001002')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 10.00,
                'aplica_retencion_ica' => true,
                'porcentaje_retencion_ica' => 0.966,
                'aplica_estampilla' => false,
                'porcentaje_estampilla' => 0,
                'banco' => 'Davivienda',
                'tipo_cuenta' => 'corriente',
                'numero_cuenta' => '99900011122',
                'requiere_seguridad_social' => false,
                'adjunta_planilla_pago' => false,
                'requiere_poliza' => false,
                'estado' => 'activo',
            ],
            [
                'numero_contrato' => 'CT-2026-008',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->addMonths(1)->startOfMonth(),
                'fecha_fin' => now()->addMonths(4)->endOfMonth(),
                'plazo_meses' => 3,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '9999000011',
                'nombre_contratista' => 'Sergio Mejía González',
                'email_contratista' => 'sergio.mejia@example.com',
                'telefono_contratista' => '3204444444',
                'direccion_contratista' => 'Transversal 60 # 40-70',
                'ciudad_contratista' => 'Cali',
                'valor_total' => 15000000,
                'valor_mensual' => 5000000,
                'valor_pagado' => 0,
                'saldo_pendiente' => 15000000,
                'objeto' => 'Mantenimiento preventivo de equipos de cómputo',
                'obligaciones' => 'Mantenimiento mensual, soporte técnico, reportes de estado',
                'supervisor_nombre' => 'Jefe de Tecnología',
                'centro_costo_id' => $centrosCosto->where('codigo', '004002')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 10.00,
                'aplica_retencion_ica' => false,
                'porcentaje_retencion_ica' => 0,
                'aplica_estampilla' => false,
                'porcentaje_estampilla' => 0,
                'banco' => 'Bancolombia',
                'tipo_cuenta' => 'ahorros',
                'numero_cuenta' => '11122233344',
                'requiere_seguridad_social' => false,
                'adjunta_planilla_pago' => false,
                'requiere_poliza' => false,
                'estado' => 'activo',
            ],
            
            // ════ TERMINADOS (4 contratos) ════
            [
                'numero_contrato' => 'CT-2025-045',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->subMonths(8)->startOfMonth(),
                'fecha_fin' => now()->subMonths(2)->endOfMonth(),
                'plazo_meses' => 6,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '8888999900',
                'nombre_contratista' => 'Patricia Gómez Vargas',
                'email_contratista' => 'patricia.gomez@example.com',
                'telefono_contratista' => '3002223344',
                'direccion_contratista' => 'Calle 50 # 20-30',
                'ciudad_contratista' => 'Medellín',
                'valor_total' => 15000000,
                'valor_mensual' => 2500000,
                'valor_pagado' => 15000000,
                'saldo_pendiente' => 0,
                'objeto' => 'Consultoría en gestión del talento humano',
                'obligaciones' => 'Diagnóstico organizacional, plan de mejoramiento, capacitación',
                'supervisor_nombre' => 'Roberto Silva',
                'centro_costo_id' => $centrosCosto->where('codigo', '001002')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 11.00,
                'aplica_retencion_ica' => false,
                'porcentaje_retencion_ica' => 0,
                'aplica_estampilla' => false,
                'porcentaje_estampilla' => 0,
                'banco' => 'BBVA',
                'tipo_cuenta' => 'ahorros',
                'numero_cuenta' => '77788899900',
                'requiere_seguridad_social' => true,
                'adjunta_planilla_pago' => true,
                'requiere_poliza' => false,
                'estado' => 'terminado',
                'fecha_terminacion_real' => now()->subMonths(2)->endOfMonth(),
            ],
            [
                'numero_contrato' => 'CT-2025-046',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->subMonths(10)->startOfMonth(),
                'fecha_fin' => now()->subMonths(4)->endOfMonth(),
                'plazo_meses' => 6,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '1010101010',
                'nombre_contratista' => 'Luis Miguel Cordero Salazar',
                'email_contratista' => 'luis.cordero@example.com',
                'telefono_contratista' => '3025555555',
                'direccion_contratista' => 'Carrera 15 # 60-80',
                'ciudad_contratista' => 'Bogotá',
                'valor_total' => 18000000,
                'valor_mensual' => 3000000,
                'valor_pagado' => 18000000,
                'saldo_pendiente' => 0,
                'objeto' => 'Desarrollo de reportes avanzados en Power BI',
                'obligaciones' => 'Desarrollo de dashboards, training al equipo, documentación',
                'supervisor_nombre' => 'Analista Financiero',
                'centro_costo_id' => $centrosCosto->where('codigo', '001003')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 10.00,
                'aplica_retencion_ica' => false,
                'porcentaje_retencion_ica' => 0,
                'aplica_estampilla' => false,
                'porcentaje_estampilla' => 0,
                'banco' => 'Davivienda',
                'tipo_cuenta' => 'corriente',
                'numero_cuenta' => '33344455566',
                'requiere_seguridad_social' => true,
                'adjunta_planilla_pago' => true,
                'requiere_poliza' => true,
                'numero_poliza' => 'POL-2025-001',
                'aseguradora' => 'Seguros Monterrey',
                'fecha_vencimiento_poliza' => now()->subMonths(4),
                'estado' => 'terminado',
                'fecha_terminacion_real' => now()->subMonths(4)->endOfMonth(),
            ],
            [
                'numero_contrato' => 'CT-2025-047',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->subMonths(9)->startOfMonth(),
                'fecha_fin' => now()->subMonths(3)->endOfMonth(),
                'plazo_meses' => 6,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '1212121212',
                'nombre_contratista' => 'Alejandro Torres Marín',
                'email_contratista' => 'alejandro.torres@example.com',
                'telefono_contratista' => '3036666666',
                'direccion_contratista' => 'Avenida 50 # 60-80',
                'ciudad_contratista' => 'Bogotá',
                'valor_total' => 21000000,
                'valor_mensual' => 3500000,
                'valor_pagado' => 21000000,
                'saldo_pendiente' => 0,
                'objeto' => 'Implementación de procesos de calidad ISO 9001',
                'obligaciones' => 'Auditoría inicial, diseño de procesos, capacitación, certificación',
                'supervisor_nombre' => 'Gerencia General',
                'centro_costo_id' => $centrosCosto->where('codigo', '002003')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 11.00,
                'aplica_retencion_ica' => false,
                'porcentaje_retencion_ica' => 0,
                'aplica_estampilla' => false,
                'porcentaje_estampilla' => 0,
                'banco' => 'Banco de Bogotá',
                'tipo_cuenta' => 'corriente',
                'numero_cuenta' => '44455566677',
                'requiere_seguridad_social' => false,
                'adjunta_planilla_pago' => false,
                'requiere_poliza' => false,
                'estado' => 'terminado',
                'fecha_terminacion_real' => now()->subMonths(3)->endOfMonth(),
            ],
            [
                'numero_contrato' => 'CT-2025-048',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->subMonths(7)->startOfMonth(),
                'fecha_fin' => now()->subMonths(1)->endOfMonth(),
                'plazo_meses' => 6,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '1313131313',
                'nombre_contratista' => 'Deisy Ramírez Morales',
                'email_contratista' => 'deisy.ramirez@example.com',
                'telefono_contratista' => '3047777777',
                'direccion_contratista' => 'Calle 100 # 15-30',
                'ciudad_contratista' => 'Bogotá',
                'valor_total' => 12000000,
                'valor_mensual' => 2000000,
                'valor_pagado' => 12000000,
                'saldo_pendiente' => 0,
                'objeto' => 'Servicios de traducción a inglés de documentos corporativos',
                'obligaciones' => 'Traducción de manuales, reportes y comunicados, revisión de calidad',
                'supervisor_nombre' => 'Gerencia de Ventas',
                'centro_costo_id' => $centrosCosto->where('codigo', '003001')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 10.00,
                'aplica_retencion_ica' => true,
                'porcentaje_retencion_ica' => 0.966,
                'aplica_estampilla' => false,
                'porcentaje_estampilla' => 0,
                'banco' => 'Davivienda',
                'tipo_cuenta' => 'ahorros',
                'numero_cuenta' => '55566677788',
                'requiere_seguridad_social' => false,
                'adjunta_planilla_pago' => false,
                'requiere_poliza' => false,
                'estado' => 'terminado',
                'fecha_terminacion_real' => now()->subMonths(1)->endOfMonth(),
            ],
            
            // ════ SUSPENDIDOS (3 contratos) ════
            [
                'numero_contrato' => 'CT-2026-009',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->subMonths(3)->startOfMonth(),
                'fecha_fin' => now()->addMonths(3)->endOfMonth(),
                'plazo_meses' => 6,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '2020202020',
                'nombre_contratista' => 'Jhon Stefan Morales Castro',
                'email_contratista' => 'jhon.morales@example.com',
                'telefono_contratista' => '3058888888',
                'direccion_contratista' => 'Transversal 30 # 70-90',
                'ciudad_contratista' => 'Bogotá',
                'valor_total' => 10000000,
                'valor_mensual' => 1666667,
                'valor_pagado' => 3333334,
                'saldo_pendiente' => 6666666,
                'objeto' => 'Servicios de fotografía y video corporativo',
                'obligaciones' => 'Producción de video institucional, fotografía de eventos, edición',
                'supervisor_nombre' => 'Marketing',
                'centro_costo_id' => $centrosCosto->where('codigo', '003003')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 10.00,
                'aplica_retencion_ica' => true,
                'porcentaje_retencion_ica' => 0.966,
                'aplica_estampilla' => false,
                'porcentaje_estampilla' => 0,
                'banco' => 'Bancolombia',
                'tipo_cuenta' => 'ahorros',
                'numero_cuenta' => '66677788899',
                'requiere_seguridad_social' => false,
                'adjunta_planilla_pago' => false,
                'requiere_poliza' => false,
                'estado' => 'suspendido',
                'observaciones' => 'Suspendido desde ' . now()->subMonths(1)->format('Y-m-d') . '\nMotivo: Por reestructuración de procesos de marketing',
            ],
            [
                'numero_contrato' => 'CT-2026-010',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->subMonths(2)->startOfMonth(),
                'fecha_fin' => now()->addMonths(4)->endOfMonth(),
                'plazo_meses' => 6,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '2121212121',
                'nombre_contratista' => 'Francisca Méndez Reyes',
                'email_contratista' => 'francisca.mendez@example.com',
                'telefono_contratista' => '3069999999',
                'direccion_contratista' => 'Calle 95 # 20-50',
                'ciudad_contratista' => 'Bogotá',
                'valor_total' => 8000000,
                'valor_mensual' => 1333333,
                'valor_pagado' => 2666666,
                'saldo_pendiente' => 5333334,
                'objeto' => 'Servicios de limpieza y mantenimiento de oficinas',
                'obligaciones' => 'Limpieza diaria, mantenimiento de áreas comunes, gestión de residuos',
                'supervisor_nombre' => 'Administración',
                'centro_costo_id' => $centrosCosto->where('codigo', '001001')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 10.00,
                'aplica_retencion_ica' => false,
                'porcentaje_retencion_ica' => 0,
                'aplica_estampilla' => false,
                'porcentaje_estampilla' => 0,
                'banco' => 'Davivienda',
                'tipo_cuenta' => 'ahorros',
                'numero_cuenta' => '77788899900',
                'requiere_seguridad_social' => true,
                'adjunta_planilla_pago' => true,
                'requiere_poliza' => false,
                'estado' => 'suspendido',
                'observaciones' => 'Suspendido desde ' . now()->subMonths(1)->format('Y-m-d') . '\nMotivo: Cambio de proveedor de servicios generales',
            ],
            [
                'numero_contrato' => 'CT-2026-011',
                'tipo_contrato' => 'prestacion_servicios',
                'fecha_inicio' => now()->subMonths(4)->startOfMonth(),
                'fecha_fin' => now()->addMonths(2)->endOfMonth(),
                'plazo_meses' => 6,
                'tipo_documento_contratista' => 'CC',
                'numero_documento_contratista' => '2222333344',
                'nombre_contratista' => 'Empresas Unidas de Vigilancia S.A.',
                'email_contratista' => 'contacto@euv.com.co',
                'telefono_contratista' => '3070000000',
                'direccion_contratista' => 'Carrera 70 # 80-15',
                'ciudad_contratista' => 'Bogotá',
                'valor_total' => 36000000,
                'valor_mensual' => 6000000,
                'valor_pagado' => 18000000,
                'saldo_pendiente' => 18000000,
                'objeto' => 'Servicios de vigilancia y seguridad de instalaciones',
                'obligaciones' => 'Vigilancia 24/7, control de acceso, monitoreo de cámaras, reportes',
                'supervisor_nombre' => 'Seguridad Física',
                'centro_costo_id' => $centrosCosto->where('codigo', '001001')->first()?->id,
                'aplica_retencion_fuente' => true,
                'porcentaje_retencion_fuente' => 10.00,
                'aplica_retencion_ica' => false,
                'porcentaje_retencion_ica' => 0,
                'aplica_estampilla' => true,
                'porcentaje_estampilla' => 3.0,
                'banco' => 'Banco de Bogotá',
                'tipo_cuenta' => 'corriente',
                'numero_cuenta' => '88899900011',
                'requiere_seguridad_social' => true,
                'adjunta_planilla_pago' => true,
                'requiere_poliza' => true,
                'numero_poliza' => 'POL-EUV-2026',
                'aseguradora' => 'AXA Colpatria',
                'fecha_vencimiento_poliza' => now()->addMonths(2),
                'estado' => 'suspendido',
                'observaciones' => 'Suspendido desde ' . now()->subWeeks(2)->format('Y-m-d') . '\nMotivo: Pendiente de revisión de pólizas de responsabilidad',
            ],
        ];

        foreach ($contratos as $contrato) {
            Contrato::create($contrato);
        }
        
        $this->command->info('✓ ' . count($contratos) . ' contratos creados exitosamente (8 activos, 4 terminados, 3 suspendidos)');
    }
}